### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by hannaoyo** [hannaoyo/furima-39933#22]
# URL
https://furimaapp-39933.onrender.com

# Basic認証のIDとパスワード 
admin
2222

# 出品者用のメールアドレスとパスワード 
test3@yahoo.co.jp
testyou1

# 購入者用のメールアドレスとパスワード
test4@yahoo.co.jp
testyou1

**Comment by snkw-works** [comment]
@hannaoyo さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
#### 商品一覧表示機能
- [x] **商品が出品されていない状態では、ダミーの商品情報が表示されるようにしましょう**
今回、商品が出品された状態でご提出いただいたため、こちらの項目が確認できませんでした。次回ご提出時にはDBをリセットした状態でご提出くださいますよう、よろしくお願いいたします。（詳細はカリキュラムをご確認ください。）

#### 商品出品機能
- [x] **発送元の地域は、「---」と47都道府県の合計48項目が表示されるよう修正しましょう（--- は初期値として設定すること）**
「千葉県」が抜けています。

- [x] **入力された販売価格によって、販売手数料や販売利益が変わるよう修正しましょう(JavaScriptを使用して実装すること)**
販売価格を入力しても、手数料や販売利益が表示されない状態です。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by snkw-works** [comment]
@hannaoyo さん、修正とご提出ありがとうございます‼︎
正常に動作することが確認できました！ **LGTM** です✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)
